[theme]
primaryColor = "#126443"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F7F5"
textColor = "#18221F"
font = "sans-serif"

[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false

